# Generated by Django 4.2.3 on 2023-11-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.course')),
            ],
            options={
                'unique_together': {('code', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VMS', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('program_year', models.CharField(max_length=15, null=True)),
                ('student_type', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=10, null=True)),
                ('nationality', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.student')),
            ],
        ),
    ]
