# Generated by Django 4.2.3 on 2023-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
