# Generated by Django 4.2.3 on 2023-12-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_task_upload_ticket_upload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('code', 'type', 'course_code')},
        ),
    ]
