# Generated by Django 4.2.3 on 2023-12-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_useraccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccess',
            old_name='status',
            new_name='access',
        ),
    ]
