# Generated by Django 4.2.3 on 2024-01-10 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('details', models.TextField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_thread', to='quickstart.task')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
