# Generated by Django 4.2.3 on 2024-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_remove_task_upload_remove_ticket_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
