# Generated by Django 4.2.3 on 2024-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_alter_task_ta_alter_task_group_alter_task_prof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
