# Generated by Django 4.2.3 on 2024-01-05 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 8, 53, 15, 458203, tzinfo=datetime.timezone.utc)),
        ),
    ]
