# Generated by Django 4.2.3 on 2024-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_faq_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='upload',
        ),
        migrations.AddField(
            model_name='task',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
