# Generated by Django 4.2.3 on 2024-01-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_user_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='final_comment',
        ),
    ]
