# Generated by Django 4.2.3 on 2024-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_remove_ticket_final_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskthread',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskthread',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
