# Generated by Django 4.2.3 on 2024-02-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_taskthread_file_name_taskthread_url_thread_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task_group', to='quickstart.group'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticket_group', to='quickstart.group'),
        ),
    ]
