# Generated by Django 4.2.3 on 2024-02-26 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_task_group_ticket_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_TA', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_Ta', to='quickstart.group')),
            ],
        ),
    ]
